services:
  db:
    image: mysql:8
    container_name: mybudget-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mybudget
      MYSQL_USER: mybudgetuser
      MYSQL_PASSWORD: mybudgetpass
    ports:
      - "3307:3306"
    volumes:
      - mybudget-db-data:/var/lib/mysql
    networks:
      - mybudget-network

backend:
  image: openjdk:24-jdk
  container_name: mybudget-backend
  depends_on:
    - db
  ports:
    - "8080:8080"
  volumes:
    - ./target/mybudget-0.0.1-SNAPSHOT.jar:/app/mybudget.jar
  working_dir: /app
  command: ["java", "-jar", "mybudget.jar"]
  environment:
    SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/mybudget?useSSL=false&serverTimezone=UTC
    SPRING_DATASOURCE_USERNAME: mybudgetuser
    SPRING_DATASOURCE_PASSWORD: mybudgetpass
    SPRING_JPA_HIBERNATE_DDL_AUTO: update
  networks:
    - mybudget-network
  restart: on-failure

volumes:
  mybudget-db-data:

networks:
  mybudget-network:
